import esbuild from "esbuild";
import { readFileSync } from "node:fs";
import { builtinModules } from "node:module";
import process from "node:process";
import { gzipSync } from "node:zlib";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, visit the plugin's GitHub repository
https://github.com/harehare/obsidian-mq
*/
`;

const production = process.argv[2] === "production";

// wasm-pack's `--target web` output ships a raw, uncompressed .wasm binary (~4.8 MB for
// mq-web), which alone pushes main.js past Obsidian Sync's 5 MB per-file limit once
// base64-inlined. This plugin onLoad gzips it before esbuild's "dataurl" loader
// base64-encodes it, and src/mq/wasm.ts inflates it again at runtime with
// `DecompressionStream("gzip")` before instantiating.
const wasmGzipPlugin = {
  name: "wasm-gzip",
  setup(build) {
    build.onLoad({ filter: /\.wasm$/ }, (args) => ({
      contents: gzipSync(readFileSync(args.path), { level: 9 }),
      loader: "dataurl",
    }));
  },
};

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
  ],
  format: "cjs",
  target: "es2022",
  logLevel: "info",
  sourcemap: production ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: production,
  plugins: [wasmGzipPlugin],
});

if (production) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
