import esbuild from "esbuild";
import process from "node:process";
import builtins from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, visit the plugin's GitHub repository
https://github.com/harehare/obsidian-mq
*/
`;

const production = process.argv[2] === "production";

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2022",
  logLevel: "info",
  sourcemap: production ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: production,
  // wasm-pack's `--target web` output ships a raw .wasm binary. The "dataurl" loader
  // embeds it as a `data:application/wasm;base64,...` string, decoded by hand in
  // src/mq/wasm.ts with `atob`. The "binary" loader looks more direct (a Uint8Array
  // import) but its generated decoder calls `Uint8Array.fromBase64`, a very new API
  // that Obsidian's bundled Electron/Chromium doesn't have yet — that silently breaks
  // wasm init at runtime (see src/mq/wasm.ts). Either way this never needs `fetch()`,
  // which keeps the plugin working offline and on mobile.
  loader: {
    ".wasm": "dataurl",
  },
});

if (production) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
